In [3]:
import pandas as pd
import numpy as np
# generate a dataframe with this data
patron_type_code ={0, 1, 2, 3, 4, 5, 10}
patron_type_definition= {'SENIOR', 'JUVENILE', 'YOUNG ADULT', 'ADULT', 'VISITOR', 'STAFF', 'WELCOME'}
total_checkouts ={0, 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 15, 402, 19, 20, 23, 24, 281, 26, 27, 156, 25, 35, 36, 38, 4011, 177, 50, 56, 184, 314, 1211, 1089, 68, 72, 74, 1098, 79, 81, 210, 980, 84, 98, 100, 2279, 377, 623, 629, 885, 376, 1913, 5627}
total_renewals ={0, 1, 2, 3, 4, 256, 6, 5, 8, 9, 12, 14, 656, 16, 19, 23, 151, 26, 31, 32, 40, 46, 47, 1072, 2355, 63, 196, 75, 973, 745, 107, 117, 378}
age_range ={'45 to 54 years', '0 to 9 years', '35 to 44 years', '25 to 34 years', '75 years and over', '10 to 19 years', '60 to 64 years', '55 to 59 years', '65 to 74 years', '20 to 24 years'}
home_library_code ={'W2', 'M4', 'M6', 'P5', 'A5', 'P1', 'R3', 'P7', 'P3', 'C2', 'B4', 'M8', 'E9', 'G6', 'G4', 'X', 'V3', 'O7', 'M2', 'E7', 'S7', 'N6', 'W4', 'I5', 'N4'}
home_library_definition ={'Chinatown', 'Mission', 'Eureka Valley/Harvey Milk Memorial', 'Parkside', 'Marina', 'West Portal', 'Sunset', 'Ingleside', 'Golden Gate Valley', 'Mission Bay', 'Merced', 'Western Addition', 'Noe Valley/Sally Brunn', 'Potrero', 'Excelsior', 'Anza', 'Ortega', 'Visitacion Valley', 'North Beach', 'Bernal Heights', 'Glen Park', 'Main Library', 'Richmond', 'Park', 'Portola'}
circulation_active_month ={'October', None, 'September', 'April', 'May', 'July', 'February', 'June', 'March', 'August', 'November', 'January'}
circulation_active_year ={ 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0}
notice_preference_code ={'z', 'a', 'p'}
notice_preference_definition ={'email', 'print', 'phone'}
provided_email_address ={False, True}
year_patron_registered ={2016, 2003, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015}
outside_of_county ={False, True}
supervisor_district={ 1.0, 3.0, 2.0, 5.0, 4.0, 7.0, 8.0, 9.0, 10.0, 11.0,  6.0}

# create a dataframe with this data

In [5]:
# create a dataframe with this data
len_of_columns = 1000
df = pd.DataFrame({'patron_type_code': np.random.choice(list(patron_type_code), len_of_columns),
                     'patron_type_definition': np.random.choice(list(patron_type_definition), len_of_columns),
                        'total_checkouts': np.random.choice(list(total_checkouts), len_of_columns),
                        'total_renewals': np.random.choice(list(total_renewals), len_of_columns),
                        'age_range': np.random.choice(list(age_range), len_of_columns),
                        'home_library_code': np.random.choice(list(home_library_code), len_of_columns),
                        'home_library_definition': np.random.choice(list(home_library_definition), len_of_columns),
                        'circulation_active_month': np.random.choice(list(circulation_active_month), len_of_columns),

                        'circulation_active_year': np.random.choice(list(circulation_active_year), len_of_columns),
                        'notice_preference_code': np.random.choice(list(notice_preference_code), len_of_columns),
                        'notice_preference_definition': np.random.choice(list(notice_preference_definition), len_of_columns),
                        'provided_email_address': np.random.choice(list(provided_email_address), len_of_columns),
                        'year_patron_registered': np.random.choice(list(year_patron_registered), len_of_columns),
                        'outside_of_county': np.random.choice(list(outside_of_county), len_of_columns),
                        'supervisor_district': np.random.choice(list(supervisor_district), len_of_columns)
                        })

,patron_type_code,patron_type_definition,total_checkouts,total_renewals,age_range,home_library_code,home_library_definition,circulation_active_month,circulation_active_year,notice_preference_code,notice_preference_definition,provided_email_address,year_patron_registered,outside_of_county,supervisor_district
0,3,SENIOR,376,12,10 to 19 years,W4,West Portal,October,2008.0,a,email,False,2015,True,4.0
1,2,ADULT,156,40,55 to 59 years,C2,Chinatown,January,2016.0,z,print,True,2005,False,5.0
2,2,JUVENILE,281,32,35 to 44 years,G4,Park,October,2013.0,z,print,False,2007,False,1.0
3,3,VISITOR,56,5,55 to 59 years,C2,Sunset,February,2008.0,p,phone,True,2007,True,4.0
4,5,VISITOR,11,19,0 to 9 years,X,Merced,September,2008.0,a,print,True,2012,True,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1,JUVENILE,9,378,55 to 59 years,P3,Ortega,November,2009.0,z,print,False,2009,False,9.0
996,2,YOUNG ADULT,376,107,20 to 24 years,V3,Bernal Heights,August,2016.0,z,email,True,2007,False,2.0
997,10,JUVENILE,4011,378,75 years and over,M8,Visitacion Valley,October,2016.0,z,email,True,2006,False,7.0
998,10,VISITOR,4011,973,60 to 64 years,I5,Noe Valley/Sally Brunn,May,2009.0,p,print,False,2010,True,3.0
999,10,STAFF,6,378,10 to 19 years,G6,Eureka Valley/Harvey Milk Memorial,January,2012.0,z,phone,True,2014,True,7.0

In [15]:
con1=df['provided_email_address']==False
con2=df['circulation_active_year']==2016
con3=df['notice_preference_definition']=='email'
df[con1&con2&con3]['home_library_code'].unique()

array(['O7', 'B4', 'W4', 'A5', 'N4', 'N6', 'X', 'M4', 'E7', 'R3', 'P1'],
      dtype=object)