In [1]:
import pandas as pd

In [2]:
player_id = [401, 401, 401, 401, 401, 401, 401, 401, 401, 401, 402, 402, 402, 402, 402, 402, 402, 402, 402, 402, 403, 403, 403, 403, 403, 403, 403, 403, 403, 403, 404, 404, 404, 404, 404, 404, 404, 404, 404, 405, 405, 405, 405, 405, 405, 405, 405, 405, 405]
match_date = ['2021-05-04 00:00:00', '2021-05-09 00:00:00', '2021-05-16 00:00:00', '2021-05-18 00:00:00', '2021-05-22 00:00:00', '2021-06-15 00:00:00', '2021-06-16 00:00:00', '2021-06-18 00:00:00', '2021-07-06 00:00:00', '2021-07-13 00:00:00', '2021-05-14 00:00:00', '2021-05-23 00:00:00', '2021-05-24 00:00:00', '2021-06-01 00:00:00', '2021-06-02 00:00:00', '2021-07-01 00:00:00', '2021-07-11 00:00:00', '2021-07-20 00:00:00', '2021-07-26 00:00:00', '2021-07-30 00:00:00', '2021-05-03 00:00:00', '2021-05-11 00:00:00', '2021-05-12 00:00:00', '2021-05-13 00:00:00', '2021-05-20 00:00:00', '2021-05-25 00:00:00', '2021-07-06 00:00:00', '2021-07-15 00:00:00', '2021-07-22 00:00:00', '2021-07-23 00:00:00', '2021-05-10 00:00:00', '2021-05-16 00:00:00', '2021-05-20 00:00:00', '2021-05-22 00:00:00', '2021-05-28 00:00:00', '2021-06-06 00:00:00', '2021-06-14 00:00:00', '2021-07-25 00:00:00', '2021-07-26 00:00:00', '2021-05-07 00:00:00', '2021-05-25 00:00:00', '2021-06-06 00:00:00', '2021-06-07 00:00:00', '2021-06-14 00:00:00', '2021-07-01 00:00:00', '2021-07-02 00:00:00', '2021-07-14 00:00:00', '2021-07-16 00:00:00', '2021-07-30 00:00:00']
match_result = ['W', 'L', 'L', 'W', 'L', 'L', 'W', 'W', 'L', 'L', 'L', 'L', 'W', 'W', 'W', 'W', 'W', 'L', 'L', 'L', 'L', 'W', 'W', 'W', 'W', 'W', 'L', 'L', 'W', 'W', 'W', 'W', 'W', 'W', 'L', 'L', 'W', 'W', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'W', 'L', 'L']
df=pd.DataFrame({'player_id':player_id,'match_date':match_date,'match_result':match_result})
temp=[]
for i in df.match_date:
    temp.append(pd.Timestamp(i))
df.match_date=temp

In [7]:
#sort the dataframe by match_date and player_id
df=df.sort_values(by=['player_id','match_date'])
df

    player_id match_date match_result
0         401 2021-05-04            W
1         401 2021-05-09            L
2         401 2021-05-16            L
3         401 2021-05-18            W
4         401 2021-05-22            L
5         401 2021-06-15            L
6         401 2021-06-16            W
7         401 2021-06-18            W
8         401 2021-07-06            L
9         401 2021-07-13            L
10        402 2021-05-14            L
11        402 2021-05-23            L
12        402 2021-05-24            W
13        402 2021-06-01            W
14        402 2021-06-02            W
15        402 2021-07-01            W
16        402 2021-07-11            W
17        402 2021-07-20            L
18        402 2021-07-26            L
19        402 2021-07-30            L
20        403 2021-05-03            L
21        403 2021-05-11            W
22        403 2021-05-12            W
23        403 2021-05-13            W
24        403 2021-05-20            W
25        403 2021-05-25            W
26        403 2021-07-06            L
27        403 2021-07-15            L
28        403 2021-07-22            W
29        403 2021-07-23            W
30        404 2021-05-10            W
31        404 2021-05-16            W
32        404 2021-05-20            W
33        404 2021-05-22            W
34        404 2021-05-28            L
35        404 2021-06-06            L
36        404 2021-06-14            W
37        404 2021-07-25            W
38        404 2021-07-26            L
39        405 2021-05-07            L
40        405 2021-05-25            L
41        405 2021-06-06            L
42        405 2021-06-07            L
43        405 2021-06-14            L
44        405 2021-07-01            L
45        405 2021-07-02            L
46        405 2021-07-14            W
47        405 2021-07-16            L
48        405 2021-07-30            L

In [4]:
res={}
for i in range(len(df)):
    row=df.iloc[i]

   player_id match_date match_result  winning_streak
0        401 2021-05-04            W               1
1        401 2021-05-09            L               1
2        401 2021-05-16            L               1
3        401 2021-05-18            W               2
4        401 2021-05-22            L               2
5        401 2021-06-15            L               2
6        401 2021-06-16            W               3
7        401 2021-06-18            W               4
8        401 2021-07-06            L               4
9        401 2021-07-13            L               4