In [6]:
import pandas as pd

In [7]:
post_id = [0, 1, 2, 3, 4, 5]
poster = [2, 1, 2, 1, 3, 3]
post_text = ['The Lakers game from last night was great.', 'Lebron James is top class.', 'Asparagus tastes OK.', 'Spaghetti is an Italian food.', 'User 3 is not sharing interests', 'User 3 posts SPAM content a lot']
post_keywords = ['[basketball,lakers,nba]', '[basketball,lebron_james,nba]', '[asparagus,food]', '[spaghetti,food]', '[#spam#]', '[#spam#]']
post_date = ['2019-01-01 00:00:00', '2019-01-02 00:00:00', '2019-01-01 00:00:00', '2019-01-02 00:00:00', '2019-01-01 00:00:00', '2019-01-02 00:00:00']
df=pd.DataFrame({'post_id':post_id,'poster':poster,'post_text':post_text,'post_keywords':post_keywords,'post_date':post_date})
temp=[]
for i in df.post_date:
    temp.append(pd.Timestamp(i))
df.post_date=temp
df

,post_id,poster,post_text,post_keywords,post_date
0,0,2,The Lakers game from last night was great.,"[basketball,lakers,nba]",2019-01-01
1,1,1,Lebron James is top class.,"[basketball,lebron_james,nba]",2019-01-02
2,2,2,Asparagus tastes OK.,"[asparagus,food]",2019-01-01
3,3,1,Spaghetti is an Italian food.,"[spaghetti,food]",2019-01-02
4,4,3,User 3 is not sharing interests,[#spam#],2019-01-01
5,5,3,User 3 posts SPAM content a lot,[#spam#],2019-01-02

In [8]:
post_id = [4, 4, 4, 5, 5, 5, 3, 3, 3]
viewer_id = [0, 1, 2, 0, 1, 2, 1, 2, 3]
df2=pd.DataFrame({'post_id':post_id,'viewer_id':viewer_id})

In [14]:
df3=pd.merge(df,df2,on='post_id',how='outer')
df3

,post_id,poster,post_text,post_keywords,post_date,viewer_id
0,0,2,The Lakers game from last night was great.,"[basketball,lakers,nba]",2019-01-01,NaN
1,1,1,Lebron James is top class.,"[basketball,lebron_james,nba]",2019-01-02,NaN
2,2,2,Asparagus tastes OK.,"[asparagus,food]",2019-01-01,NaN
3,3,1,Spaghetti is an Italian food.,"[spaghetti,food]",2019-01-02,1.0
4,3,1,Spaghetti is an Italian food.,"[spaghetti,food]",2019-01-02,2.0
5,3,1,Spaghetti is an Italian food.,"[spaghetti,food]",2019-01-02,3.0
6,4,3,User 3 is not sharing interests,[#spam#],2019-01-01,0.0
7,4,3,User 3 is not sharing interests,[#spam#],2019-01-01,1.0
8,4,3,User 3 is not sharing interests,[#spam#],2019-01-01,2.0
9,5,3,User 3 posts SPAM content a lot,[#spam#],2019-01-02,0.0
10,5,3,User 3 posts SPAM content a lot,[#spam#],2019-01-02,1.0
11,5,3,User 3 posts SPAM content a lot,[#spam#],2019-01-02,2.0

In [28]:
res={}
for _,row in df3.iterrows():
    words=row.post_keywords[1:-1].split(',')
    for word in words:
        
        if word not in res:
            res[word]=0
        if not pd.isnull(row.viewer_id ):
            res[word]+=1
#change the key of #spam# to spam
res['spam']=res.pop('#spam#')
res=pd.DataFrame({'keyword':list(res.keys()),'total_views':list(res.values())})
res.sort_values(by='total_views',ascending=False)

        keyword  total_views
7          spam            6
5          food            3
6     spaghetti            3
0    basketball            0
1        lakers            0
2           nba            0
3  lebron_james            0
4     asparagus            0